package com.axway.apim.test.apiExport;

import org.springframework.beans.factory.annotation.Autowired;
import org.testng.annotations.Test;

import com.axway.apim.test.ExportTestAction;
import com.axway.apim.test.ImportTestAction;
import com.consol.citrus.annotations.CitrusTest;
import com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner;
import com.consol.citrus.functions.core.RandomNumberFunction;

@Test
public class ImageAPIExportTestIt extends TestNGCitrusTestDesigner {
	
	@Autowired
	private ExportTestAction exportAction;
	@Autowired
	private ImportTestAction importAction;
	
	@CitrusTest
	public void run() {
		description("Import an API with an Image, export it and Re-Import. Should lead to a no-change!");
		
		
		variable("handleNullAsChange", "true"); // Enforce to check all properties!
		variable("apiNumber", RandomNumberFunction.getRandomNumber(3, true));
		variable("apiPath", "/api/test/"+this.getClass().getSimpleName()+"-${apiNumber}");
		variable("apiName", this.getClass().getSimpleName()+"-${apiNumber}");
		variable("state", "unpublished");
		variable("exportLocation", "citrus:systemProperty('java.io.tmpdir')");
		
		// These are the folder and filenames generated by the export tool 
		variable("exportFolder", "api-test-${apiName}");
		variable("exportAPIName", "${apiName}.json");

		echo("####### Importing the API, which should exported in the second step #######");
		createVariable(ImportTestAction.API_DEFINITION,  "/com/axway/apim/test/files/basic/petstore.json");
		createVariable(ImportTestAction.API_CONFIG,  "/com/axway/apim/test/files/image/2_image_included_flex_state.json");
		createVariable("image", "/com/axway/apim/test/files/basic/API-Logo.jpg");
		createVariable("expectedReturnCode", "0");
		action(importAction);

		echo("####### Export the API fromt the API-Manager #######");
		createVariable(ExportTestAction.EXPORT_API,  "${apiPath}");
		createVariable("expectedReturnCode", "0");
		action(exportAction);
		
		echo("####### Re-Import the same API and it must lead to a No-Change result #######");
		createVariable(ImportTestAction.API_DEFINITION,  "${exportLocation}${exportFolder}/${exportAPIName}");
		createVariable(ImportTestAction.API_CONFIG,  "${exportLocation}${exportFolder}/api-config.json");
		createVariable("image",  "${exportLocation}${exportFolder}/api-image.jpg");
		createVariable("expectedReturnCode", "10");
		action(importAction);
	}

}
