package com.axway.apim.test.apiExport;

import org.springframework.beans.factory.annotation.Autowired;
import org.testng.annotations.Test;

import com.axway.apim.test.ExportTestAction;
import com.axway.apim.test.ImportTestAction;
import com.consol.citrus.annotations.CitrusTest;
import com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner;
import com.consol.citrus.functions.core.RandomNumberFunction;

@Test
public class SimpleAPIExportTestIt extends TestNGCitrusTestDesigner {
	
	@Autowired
	private ExportTestAction exportAction;
	@Autowired
	private ImportTestAction importAction;
	
	@CitrusTest
	public void run() {
		description("Import an API, export it and Re-Import. Should lead to a no-change!");
		
		variable("apiNumber", RandomNumberFunction.getRandomNumber(3, true));
		variable("apiPath", "/api-for-export-${apiNumber}");
		variable("apiName", "API-For-Export-${apiNumber}");
		variable("status", "unpublished");
		variable("exportLocation", "citrus:systemProperty('java.io.tmpdir')");
		
		
		// These are the folder and filenames generated by the export tool 
		variable("exportFolder", "api-for-export-${apiNumber}");
		variable("exportAPIName", "api-for-export-${apiNumber}.json");

		echo("####### Importing the API, which should exported in the second step #######");
		createVariable(ImportTestAction.API_DEFINITION,  "/com/axway/apim/test/files/basic/petstore.json");
		createVariable(ImportTestAction.API_CONFIG,  "/com/axway/apim/test/files/basic/minimal-config.json");
		createVariable("expectedReturnCode", "0");
		action(importAction);

		echo("####### Export the API fromt the API-Manager #######");
		createVariable(ExportTestAction.EXPORT_API,  "${apiPath}");
		createVariable("expectedReturnCode", "0");
		action(exportAction);
		
		echo("####### Re-Import the same API and it must lead to a No-Change result #######");
		createVariable(ImportTestAction.API_DEFINITION,  "${exportLocation}/${exportFolder}/${exportAPIName}");
		createVariable(ImportTestAction.API_CONFIG,  "${exportLocation}/${exportFolder}/api-config.json");
		createVariable("expectedReturnCode", "10");
		action(importAction);
	}

}
